# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba052ec5b9c2fb03adb094991b1adecd65ccebea478d91a36da369d664e75ace8ec27b2e89713ef95a3fb84d1aed21e98e7de4e275565840816aac7f69bf79cd

test:
  secret_key_base: ce73a41e10744bfe5dea17bd65af9a71ebd2dc22d0a2ee7985c9e4ade2669aa7059490dbb4c6d3bb9ea69e99e97cc27648c10e3645054c37214e72af42064434

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
